Repository Beginner-coder/hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create String_reverse
  String_reverse
Labels: HACKTOBERFEST-ACCEPTED

#2 min max
  main.cpp
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest-accepted.

#3 Contributed efficiently in hacktoberfest 2022
  1_helloworld.c
  2_datatypes.c
  3_variables.c
  4_operators.c
  5_input-output.c
  contributors.css
  footer.css
  navbar.css
  style.css
  transpose.c
Labels: HACKTOBERFEST-ACCEPTED, hacktoberfest
